#define COMPONENT book
#include "\z\KNB\addons\main\script_mod.hpp"

// #define DEBUG_MODE_FULL
// #define DISABLE_COMPILE_CACHE

#ifdef DEBUG_ENABLED_BOOK
    #define DEBUG_MODE_FULL
#endif
    #ifdef DEBUG_SETTINGS_BOOK
    #define DEBUG_SETTINGS DEBUG_SETTINGS_BOOK
#endif

#include "\z\KNB\addons\main\script_macros.hpp"

#define CT_STATIC 0
#define CT_BUTTON 1
#define CT_EDIT 2
#define CT_SLIDER 3
#define CT_COMBO 4
#define CT_LISTBOX 5
#define CT_TOOLBOX 6
#define CT_CHECKBOXES 7
#define CT_PROGRESS 8
#define CT_HTML 9
#define CT_STATIC_SKEW 10
#define CT_ACTIVETEXT 11
#define CT_TREE 12
#define CT_STRUCTURED_TEXT 13
#define CT_CONTEXT_MENU 14
#define CT_CONTROLS_GROUP 15
#define CT_SHORTCUTBUTTON 16
#define CT_HITZONES 17
#define CT_VEHICLETOGGLES 18
#define CT_CONTROLS_TABLE 19
#define CT_XKEYDESC 40
#define CT_XBUTTON 41
#define CT_XLISTBOX 42
#define CT_XSLIDER 43
#define CT_XCOMBO 44
#define CT_ANIMATED_TEXTURE 45
#define CT_MENU 46
#define CT_MENU_STRIP 47
#define CT_CHECKBOX 77
#define CT_OBJECT 80
#define CT_OBJECT_ZOOM 81
#define CT_OBJECT_CONTAINER 82
#define CT_OBJECT_CONT_ANIM 83
#define CT_LINEBREAK 98
#define CT_USER 99
#define CT_MAP 100
#define CT_MAP_MAIN 101
#define CT_LISTNBOX 102
#define CT_ITEMSLOT 103
#define CT_LISTNBOX_CHECKABLE 104
#define CT_VEHICLE_DIRECTION 105

#define ST_LEFT 0x00
#define ST_RIGHT 0x01
#define ST_CENTER 0x02
#define ST_DOWN 0x04
#define ST_UP 0x08
#define ST_VCENTER 0x0C
#define ST_SINGLE 0x00
#define ST_MULTI 0x10
#define ST_TITLE_BAR 0x20
#define ST_PICTURE 0x30
#define ST_FRAME 0x40
#define ST_BACKGROUND 0x50
#define ST_GROUP_BOX 0x60
#define ST_GROUP_BOX2 0x70
#define ST_HUD_BACKGROUND 0x80
#define ST_TILE_PICTURE 0x90
#define ST_WITH_RECT 0xA0
#define ST_LINE 0xB0
#define ST_UPPERCASE 0xC0
#define ST_LOWERCASE 0xD0
#define ST_ADDITIONAL_INFO 0x0F00
#define ST_SHADOW 0x0100
#define ST_NO_RECT 0x0200
#define ST_KEEP_ASPECT_RATIO 0x0800
#define ST_TITLE ST_TITLE_BAR + ST_CENTER
#define SL_VERT 0
#define SL_HORZ 0x400
#define SL_TEXTURES 0x10
#define ST_VERTICAL 0x01
#define ST_HORIZONTAL 0
#define LB_TEXTURES 0x10
#define LB_MULTI 0x20
#define TR_SHOWROOT 1
#define TR_AUTOCOLLAPSE 2

#define IDD 2650
#define IDC_BG 2651
#define IDC_LEFT 2653
#define IDC_RIGHT 2654
#define IDC_LINEONE 2655
#define IDC_LINETWO 2656
#define IDC_LINETHREE 2657
#define IDC_LINEFOUR 2658
#define IDC_LINEFIVE 2659
#define IDC_LINESIX 2660
#define IDC_LINESEVEN 2661
#define IDC_LINEEIGHT 2662
#define IDC_LINENINE 2663

#define IDC_LINEALL [IDC_LINEONE,IDC_LINETWO,IDC_LINETHREE,IDC_LINEFOUR,IDC_LINEFIVE,IDC_LINESIX,IDC_LINESEVEN,IDC_LINEEIGHT,IDC_LINENINE]

#define IDC_CALLSIGN 2664
#define IDC_CALLSIGNTEXT 2665

#define IDC_LINEONETEXT 2666
#define IDC_LINETWOTEXT 2667
#define IDC_LINETHREETEXT 2668
#define IDC_LINEFOURTEXT 2669
#define IDC_LINEFIVETEXT 2670
#define IDC_LINESIXTEXT 2671
#define IDC_LINESEVENTEXT 2672
#define IDC_LINEEIGHTTEXT 2673
#define IDC_LINENINETEXT 2674

#define IDC_LINEALLTEXT [IDC_LINEONETEXT,IDC_LINETWOTEXT,IDC_LINETHREETEXT,IDC_LINEFOURTEXT,IDC_LINEFIVETEXT,IDC_LINESIXTEXT,IDC_LINESEVENTEXT,IDC_LINEEIGHTTEXT,IDC_LINENINETEXT]

#define IDC_CLEAR 2700

#define IDC_BLUE 2701
#define IDC_PINK 2702
#define IDC_PURPLE 2703
#define IDC_YELLOW 2704
#define IDC_RED 2705

#define IDC_EXPLAIN 2750
#define IDC_BUTTONTEXTLEFT 2751
#define IDC_BUTTONTEXTRIGHT 2752

#define IDC_CALLSIGNLINE 2800
#define IDC_LINEONELINE 2801
#define IDC_LINETWOLINE 2802
#define IDC_LINETHREELINE 2803
#define IDC_LINEFOURLINE 2804
#define IDC_LINEFIVELINE 2805
#define IDC_LINESIXLINE 2806
#define IDC_LINESEVENLINE 2807
#define IDC_LINEEIGHTLINE 2808
#define IDC_LINENINELINE 2809

#define IDC_LINEALLLINE [IDC_LINEONELINE,IDC_LINETWOLINE,IDC_LINETHREELINE,IDC_LINEFOURLINE,IDC_LINEFIVELINE,IDC_LINESIXLINE,IDC_LINESEVENLINE,IDC_LINEEIGHTLINE,IDC_LINENINELINE]

#define IDC_NOTES 2810
#define IDC_NOTES2 2811
